/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 03 10:18:45 EDT 2015
 */

package edu.allegheny.physics;

import static org.junit.Assert.*;
import org.junit.Test;
import edu.allegheny.physics.Kinetic;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.EvoSuiteFile;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, resetStaticState = true) 
public class Kinetic_ESTest extends Kinetic_ESTest_scaffolding {

  //Test case number: 0
  /*
   * 1 covered goal:
   * 1 Weak Mutation 32: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator / -> *
   */

  @Test
  public void test0()  throws Throwable  {
      String string0 = Kinetic.computeVelocity((-815), (-815));
      assertNotNull(string0);
      assertEquals("1", string0);
  }

  //Test case number: 1
  /*
   * 10 covered goals:
   * 1 Weak Mutation 11: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - ReplaceComparisonOperator == -> <=
   * 2 Weak Mutation 17: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceVariable kinetic -> velocitySquared
   * 3 Weak Mutation 18: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceVariable kinetic -> velocity
   * 4 Weak Mutation 30: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator / -> %
   * 5 Weak Mutation 33: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator * -> +
   * 6 Weak Mutation 35: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator * -> -
   * 7 Weak Mutation 37: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:12 - ReplaceVariable velocitySquared -> velocity
   * 8 Weak Mutation 38: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:12 - ReplaceVariable velocitySquared -> kinetic
   * 9 Weak Mutation 44: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:13 - ReplaceVariable velocity -> velocitySquared
   * 10 Weak Mutation 45: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:13 - ReplaceVariable velocity -> kinetic
   */

  @Test
  public void test1()  throws Throwable  {
      String string0 = Kinetic.computeVelocity(260, (-1));
      assertNotNull(string0);
      assertEquals("0", string0);
  }

  //Test case number: 2
  /*
   * 3 covered goals:
   * 1 Weak Mutation 9: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - ReplaceComparisonOperator == -> -2
   * 2 Weak Mutation 51: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:16 - ReplaceConstant - Undefined -> 
   * 3 Weak Mutation 52: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:16 - DeleteStatement: append(Ljava/lang/String;)Ljava/lang/StringBuffer;
   */

  @Test
  public void test2()  throws Throwable  {
      String string0 = Kinetic.computeVelocity((-1), 0);
      assertEquals("Undefined", string0);
      assertNotNull(string0);
  }

  //Test case number: 3
  /*
   * 39 covered goals:
   * 1 Weak Mutation 1: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:7 - ReplaceConstant - 0 -> 1
   * 2 Weak Mutation 2: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:8 - ReplaceConstant - 0 -> 1
   * 3 Weak Mutation 3: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - ReplaceVariable mass -> velocitySquared
   * 4 Weak Mutation 4: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - ReplaceVariable mass -> velocity
   * 5 Weak Mutation 5: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - ReplaceVariable mass -> kinetic
   * 6 Weak Mutation 6: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - InsertUnaryOp Negation of mass
   * 7 Weak Mutation 7: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - InsertUnaryOp IINC 1 mass
   * 8 Weak Mutation 8: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - InsertUnaryOp IINC -1 mass
   * 9 Weak Mutation 10: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:10 - ReplaceComparisonOperator == -> >=
   * 10 Weak Mutation 12: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceConstant - 3 -> 0
   * 11 Weak Mutation 13: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceConstant - 3 -> 1
   * 12 Weak Mutation 14: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceConstant - 3 -> -1
   * 13 Weak Mutation 15: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceConstant - 3 -> 2
   * 14 Weak Mutation 16: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceConstant - 3 -> 4
   * 15 Weak Mutation 19: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceVariable kinetic -> mass
   * 16 Weak Mutation 20: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - InsertUnaryOp Negation of kinetic
   * 17 Weak Mutation 21: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - InsertUnaryOp IINC 1 kinetic
   * 18 Weak Mutation 22: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - InsertUnaryOp IINC -1 kinetic
   * 19 Weak Mutation 23: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceVariable mass -> velocitySquared
   * 20 Weak Mutation 24: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceVariable mass -> velocity
   * 21 Weak Mutation 25: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceVariable mass -> kinetic
   * 22 Weak Mutation 26: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - InsertUnaryOp Negation of mass
   * 23 Weak Mutation 27: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - InsertUnaryOp IINC 1 mass
   * 24 Weak Mutation 28: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - InsertUnaryOp IINC -1 mass
   * 25 Weak Mutation 29: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator / -> +
   * 26 Weak Mutation 31: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator / -> -
   * 27 Weak Mutation 34: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator * -> %
   * 28 Weak Mutation 36: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:11 - ReplaceArithmeticOperator * -> /
   * 29 Weak Mutation 39: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:12 - ReplaceVariable velocitySquared -> mass
   * 30 Weak Mutation 40: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:12 - InsertUnaryOp Negation of velocitySquared
   * 31 Weak Mutation 41: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:12 - InsertUnaryOp IINC 1 velocitySquared
   * 32 Weak Mutation 42: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:12 - InsertUnaryOp IINC -1 velocitySquared
   * 33 Weak Mutation 43: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:12 - DeleteStatement: sqrt(D)D
   * 34 Weak Mutation 46: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:13 - ReplaceVariable velocity -> mass
   * 35 Weak Mutation 47: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:13 - InsertUnaryOp Negation of velocity
   * 36 Weak Mutation 48: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:13 - InsertUnaryOp IINC 1 velocity
   * 37 Weak Mutation 49: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:13 - InsertUnaryOp IINC -1 velocity
   * 38 Weak Mutation 50: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:13 - DeleteStatement: append(I)Ljava/lang/StringBuffer;
   * 39 Weak Mutation 53: edu.allegheny.physics.Kinetic.computeVelocity(II)Ljava/lang/String;:18 - DeleteStatement: toString()Ljava/lang/String;
   */

  @Test
  public void test3()  throws Throwable  {
      String string0 = Kinetic.computeVelocity(0, 2992);
      assertEquals("0", string0);
      assertNotNull(string0);
  }

  //Test case number: 4
  /*
   * 1 covered goal:
   * 1 Weak Mutation 0: edu.allegheny.physics.Kinetic.<init>()V:5 - DeleteStatement: registerObjectForIdentityHashCode(Ljava/lang/Object;)V
   */

  @Test
  public void test4()  throws Throwable  {
      Kinetic kinetic0 = new Kinetic();
  }
}
